# CoT Embeddings Project Configuration

# Dataset settings
dataset:
  name: "kaist-ai/CoT-Collection"
  cache_dir: "./data/cache"
  processed_dir: "./data/processed"

# Embedding settings
embedding:
  model_name: "all-mpnet-base-v2"  # Sentence transformer model
  batch_size: 32
  max_length: 512

# Vector index settings
vector_index:
  index_path: "./data/faiss_index"
  dimension: 768  # Embedding dimension for all-mpnet-base-v2
  index_type: "IndexFlatIP"  # Inner product for cosine similarity

# Retrieval settings
retrieval:
  top_k: 1  # Number of similar examples to retrieve
  similarity_threshold: 0.5

# Generation settings
generation:
  provider: "openai"  # Use OpenAI API instead of local models
  model_name: "gpt-3.5-turbo-0125"  # OpenAI model to use
  max_tokens: 512
  temperature: 0.7
  api_key: ""  # Set OPENAI_API_KEY environment variable

# System settings
system:
  device: "cuda"  # Will fallback to cpu if cuda not available
  random_seed: 42